name: Run test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    # environment variables
    - name: Add environment variables
      env:
        databaseURL: ""
        PORT: 3000


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: installl dependencies
      run: |
        npm install

    - name: build files
      run: |
        npm run build
    
    - name: test files
      run: |
        npm install
        npm test
